import type { Metadata } from "next";
import { Bubbler_One } from "next/font/google";
import "./globals.css";

const bubblerOneSans = Bubbler_One({
  variable: "--font-bubbler-one-sans",
  weight: "400",
  preload: false
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${bubblerOneSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
